### ISSUE TITLE
Call out explicitly the places where you're making some different choice about what parties are allowed to get what information

### ISSUE THREAD

**Issue by brodrigu** [MagniteEngineering/ProprietaryCohorts#5]
In #2 @michaelkleber wrote:

> To make things more understandable and internally consistent, could you go through and call out explicitly the places where you're making some different choice about what parties are allowed to get what information? The mixed messages in different parts of the doc are making it hard for me to really evaluate what you've proposed.

**Comment by brodrigu** [comment]
@michaelkleber

The hope is we don't need to apply any "gatekeeping" in this proposal to who can be a cohort provider and what they can do. The protocol described is intended to provide the required amount of privacy while also covering some advertising use-cases.

We may need to iterate to get it to that point. 

With the understanding that the only restrictions are on what can be passed to the cohort provider in the cohort registration request, do you think there is still some clarification needed? I get the sense that I just needed to clarify those other statements.

**Comment by michaelkleber** [comment]
Your "cohort provider" gets some access to information that isn't available to any server in a no-3p-cookies world (or even a world with FLoC and TURTLEDOVE/SPARROW in it), so I think it pays to be clear about who gets what.

Here's my understanding right now (after reading your answers in #3 and #4), though please let me know if any of this is wrong:

* A "cohort provider" gets to builds a profile for each user who visits any site that cooperates with that provider.
  - The user gets a unique user-ID that is only ever revealed to the cohort provider and is periodically reset.
  - Each time (or maybe "the first time since the ID was reset"?) the user visits any page on a particular domain, the cohort provider learns that domain and the approximate time of the visit, and can add that information to the profile.
  - In a proposed extension, the cohort provider learns more than just the domain, maybe getting some information about the URL also.
  - The cohort provider is _not_ supposed to be able to join the user-ID or the profile with any other information about the user.

* A site which cooperates with a cohort provider does _not_ get to learn anyone's user-ID, but _does_ get to learn any user's cohort-ID.
  - The cohort-ID is assigned by the cohort provider based on the profile, using whatever business logic the cohort provider wants.
  - There is some minimum number of people with the same cohort-ID.
  - All sites that work with the same cohort provider get the same cohort-ID for the same user.

Obviously please correct any mistakes I've main, and feel free to add or rephrase things.  But I think including something like this "here is what different parties get to know" summary will make the proposal easier to talk about.

**Comment by brodrigu** [comment]
@michaelkleber you've got the gist of it. I've added a section to call out each party and what information they can collect in #8.
